### ISSUE TITLE
pubspec.yaml: Mapping values are not allowed here. Did you miss a colon earlier?

### ISSUE THREAD

**Issue by steveLYL** [steveLYL/myFlutterApp#1]
E:\Android\flutter\flutter_windows_v0.11.3-beta\flutter\bin\flutter.bat --no-color packages get
Running "flutter packages get" in myfapp...                     
Error on line 22, column 18 of pubspec.yaml: Mapping values are not allowed here. Did you miss a colon earlier?
    english_words: ^3.1.0
                 ^

pub get failed (65)
Process finished with exit code 65

**Comment by steveLYL** [comment]
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
    english_words: ^3.1.0
```
